### ISSUE TITLE
Images do not run latest stable rustc

### ISSUE THREAD

**Issue by urschrei** [georust/docker-images#6]
They're currently on `1.43` (latest stable is `1.49`), and this has begun to cause errors, e.g. https://github.com/georust/proj/runs/1710531889

**Comment by michaelkirk** [comment]
I'll have a go at updating them now...

**Comment by michaelkirk** [comment]
Just a note that we're currently installing rustc from ubuntu 20.4, the latest version of which is 1.43

https://packages.ubuntu.com/focal/rustc

Soooooo seems like we'll have to go the rust-up way or use one of the rust containers... I don't immediately remember why we were using ubuntu base image instead of a rust base image (like https://hub.docker.com/_/rust)

**Comment by urschrei** [comment]
Oh, the official image looks more promising. I had no idea it existed.
